version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: XXXXX
    ports:
    - 8001:80
    networks:
    - symfony
  php:
    build:
      context: .
      dockerfile: XXXXX
    networks:
      - symfony
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - symfony
networks:
      symfony: